stages:
  - build
  - docs
  - deploy

include:
  - local: '.gitlab/ci/build.yml'

docs:
  image: python:3.11
  stage: docs
  before_script:
    - pip install -r docs/requirements.txt
  script:
    - sphinx-build -b html docs/source docs/build/html
  artifacts:
    paths:
      - docs/build/html
    expire_in: 1 week
  only:
    - main
    - dev

pages:
  stage: deploy
  image: python:3.11
  before_script:
    - pip install -r docs/requirements.txt
  script:
    - sphinx-build -b html docs/source public
  artifacts:
    paths:
      - public
  only:
    - main
    - dev